config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [:show] do
    post '/downgrade' => 'users#downgrade'
  end

  resources :wikis
  resources :charges, only: [:new, :create]
  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :contributing_wikis, :through => :contributions, :source => :wiki

  validates_uniqueness_of :name
  after_initialize :init, unless: :persisted?

  def self.recent_with_wikis(num)
    where('EXISTS(SELECT 1 FROM wikis WHERE user_id = users.id)').order('last_sign_in_at DESC').limit(num)
  end

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def standard?
    role == 'standard'
  end

  def init
    self.role ||= 'standard'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :contributions, dependent: :destroy
  has_many :contributors, :through => :contributions, :source => :user

  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}
  validates_uniqueness_of :title, scope: :user_id, case_sensitive: false

  after_initialize :init, unless: :persisted?

  scope :recent, ->(num) { order('updated_at DESC').where("private = ?", false).limit(num) }


  def private?
    self.private
  end

  def init
    self.private ||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    request.referrer
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :name, :email, :password, :password_confirmation
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include StripeData
  
  def new
  end

  def create
    #create a Stripe Customer object to associate with this charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Premium membership for: #{current_user.name}, #{current_user.email}",
      currency: 'usd'
      )

    flash[:notice] = "Thanks a lot, #{current_user.name}!"
    current_user.update_attributes(role: 'premium')
    redirect_to user_path(current_user)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/concerns/stripe_data.rb
require 'active_support/concern'

module StripeData
  extend ActiveSupport::Concern

  included do
    def stripe_button_data
      @stripe_button_data ||= {
        key: "#{ENV['STRIPE_PUBLISHABLE_KEY']}",
        description: "Premium Membership",
        amount: Amount.default
      }
    end
    helper_method :stripe_button_data
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :homepage, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :homepage, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  include StripeData

  def show
    @user = User.find(params[:id])
    @wikis = @user.wikis
  end

  def edit
    @user = User.find(params[:id])
    render 'devise/registrations/edit', locals: {resource: @user, resource_name: 'user'}
  end

  def downgrade
    @user = User.find(params[:user_id])
    authorize @user, :downgrade?
    @private_wikis = @user.wikis.where(private: true)
    if @user.update_attributes(role:'standard')
      flash[:notice] = "Your account role is now Standard"
      @private_wikis.each{|w|w.toggle!(:private)}
      redirect_to @user
    else
      flash[:error] = "Sorry, something went wrong. Please try again."
      redirect_to edit_user_path(@user)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include StripeData

  def index
    @wikis = Wiki.recent(10)
    @users = User.recent_with_wikis(10)
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.create(wiki_params)
    authorize @wiki

    if @wiki.save
      redirect_to @wiki
    else
      flash[:error] = @wiki.errors
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki updated!"
      redirect_to @wiki
    else
      flash[:error] = @wiki.errors
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "The wiki \"#{@wiki.title}\" has been deleted"
      redirect_to user_path(@wiki.owner)
    else
      flash[:error] = "We messed up. Please try again, or contact us"
      render :show
    end
  end

  protected

  def wiki_params
    params.require(:wiki).permit(:title,:body,:private,:contributor_ids => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
  renderer = Redcarpet::Render::HTML.new
  extensions = {no_intra_emphasis: true, fenced_code_blocks: true, autolink: true, superscript: true, underline: true }
  redcarpet = Redcarpet::Markdown.new(renderer,extensions)
  (redcarpet.render markdown).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_button.html.erb
<%= form_tag charges_path do %>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= stripe_button_data[:key] %>" data-amount=<%= stripe_button_data[:amount] %> data-description="<%= stripe_button_data[:description] %>" ></script>
 <% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : "BLOCIPEDIA"
    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body

    #top-bar.full-width
      .show-for-medium-up.medium-2.columns.text-center
        = link_to 'BLOCIPEDIA', root_path
      .small-9.medium-8.columns
        - if current_user
          Welcome, #{'&#9734;'.html_safe if current_user.premium?}#{ link_to current_user.name, user_path(current_user) } ||
          = link_to "Log out", destroy_user_session_path, method: :delete
        - else
          = render 'welcome/login'
      .small-3.medium-2.columns
        = link_to 'About', about_path
    
    = render 'welcome/show_flash'

    .row
      = yield
    

app/views/users/show.html.haml
#user-show  
  #us-right.medium-8.medium-push-4.columns
    %h2.text-center #{ @user.name }
    - if @wikis.any?
      %h3 Wikis:
      = render @wikis
    - elsif current_user != @user
      %p #{ @user.name } has not created any public wikis. If you expected to see something here, please make sure you are signed in and that #{ @user.name } has added your username (#{current_user.name}) to their list of contributors.
    - if ( current_user == @user ) 
      = link_to 'New Wiki', new_wiki_path(@wiki), class: 'button'
      %h4 Hi, #{@user.name}!
      - if current_user.standard?
        %p You are currently using the free version of Blocipedia. You may create as many Wikis as you like and share them using this URL; your readers don't need to sign in to view your Wikis. Any other Blocipedia members may login and edit your work. We think the people here are pretty nice, but if you're worried about vandalism you should probably save a local copy of your Wiki. (As of today, we do not have the capability to restore old versions of your Wikis.) You are the only person who may create or delete Wikis from your profile.

        %p We also offer a Premium Membership that allows you to choose if your Wikis are public or private. This is a great service for small organizations who need to maintain a collection of documents that all team members can easily access or edit. When you make a private Wiki, you'll be able to designate a list of Blocipedia contributors. These contributors will be the only members who can see or edit your Wikis.

        %p Ready to go Premium?
        = render 'charges/button'

      - elsif current_user.premium?
        %p Thanks for being a Premium Blocipedia Member! Your support encourages us to keep improving the site's features. As a Premium Member, you enjoy the ability to create private wikis. If you wish, you may downgrade your account back to Standard level. (Reminder: your Premium Membership does not expire, and we will never charge your account again.) If you downgrade, all of your private wikis will immediately become public. If any of your private wikis contain sensitive information, you may want to delete them before downgrading.

        =link_to 'Downgrade', user_downgrade_path(@user), class: 'button alert small', method: :post, data: {confirm: 'Are you sure you want to downgrade your account? Any of your private wikis will become public, and you will need to buy a new membership if you change your mind!'}

  #us-left.medium-4.medium-pull-8.columns
    %h4 User Info
    %ul
      %li #{@user.role.capitalize} User
      %li Has #{pluralize(@user.wikis.length, 'Wiki')}
      %li Member since #{@user.created_at.strftime('%B %-d, %Y')}
      %li Last seen on #{@user.created_at.strftime('%B %-d, %Y')}
      - if @user.homepage
        %li= link_to @user.homepage, @user.homepage
    -if @user == current_user
      =link_to 'Edit Info', edit_user_registration_path, class: 'button small'

app/views/welcome/_login.html.haml
= simple_form_for(:user, :url => session_path(:user)) do |f|
  .small-8.large-6.columns
    = f.input :name, autofocus: true, placeholder: 'username', label: false
    = f.input :password, placeholder: 'password', label: false
  .small-4.large-6.columns
    = f.button :submit, 'Log In', class: 'tiny button'
    %br
    = f.input :remember_me, label: false, inline_label: 'Remember me', as: :boolean

app/views/welcome/_show_flash.html.haml
- flashes = {:notice => 'success', :alert => 'alert', :error => 'alert'}
- flashes.each do |key, value|
  - if flash[key]
    #main-flash.alert-box.radius.text-center.large-3.small-6{'data-alert' => '', 'class' => value}
      = flash[key]
      %a.close{'href' => '#'} &times;

app/views/welcome/about.html.haml
%h1 About Blocipedia

%p Blocipedia is a wiki platform created by #{ link_to 'Spencer Neff', 'http://neffnet.net', target: '_blank' } with the help of his mentor at #{ link_to 'Bloc.io', 'http://bloc.io', target: '_blank' }. This project teaches the fundamentals of web development using Ruby on Rails. The source is hosted at #{ link_to 'Github', 'https://github.com/neffnet/blocipedia' } if you'd like to follow along.

%p Need to #{ link_to 'reset your password', new_user_password_path}?

app/views/welcome/index.html.haml
#landing.row

  .large-9.large-push-3.columns
    #info1
      %h1.text-center Welcome to Blocipedia
      %p Blocipedia is your organization's custom encyclopedia. This is a paragraph all about how great Blocipedia is. It has a call to action to sign up below.

    %ul#free.pricing-table.large-6.columns
      %li.title FREE
      %li.price $0/forever
      %li.description Create public wikis for the world to enjoy
      %li.bullet-item Use #{ link_to 'Markdown', 'https://daringfireball.net/projects/markdown/', target: '_blank' } to format your wikis simply and beautifully
      %li.bullet-item Unlimited number of wikis
      %li.bullet-item Group your wikis together in a public profile
      %li.bullet-item Any Blocipedia user may contribute to your work
      %li.cta-button
        = link_to "Sign up FREE", new_user_registration_path, class: "button success radius"

    - classes = ['pricing-table', 'large-6', 'columns', ('faded' if current_user && current_user.premium?)]
    %ul#premium{class: classes}
      %li.title &#9734; PREMIUM &#9734;
      %li.price $15 one-time-fee
      %li.description Access to all FREE features plus private wikis that you control
      %li.bullet-item Unlimited number of public or private wikis
      %li.bullet-item Designate which Blocipedia users may read or edit your wikis
      %li.bullet-item 24/7/365 award-winning customer support
      %li.cta-button
        - if current_user && !current_user.premium?
          = render 'charges/button'
        - elsif user_signed_in? && current_user.premium?
          .button.disabled
            Thanks for already going Premium!
        - else
          .button.disabled
            Please sign in first...


  #recent.large-3.large-pull-9.columns
    %h3 Recent Wikis
    %ul
    - @wikis.each do |wiki|
      %li
        = link_to wiki.title, wiki_path(wiki)
    = text_field nil, nil, placeholder: "Filter public wikis"
    %h3 Recent Users
    %ul
    - @users.each do |user|
      %li
        = link_to user.name, user_path(user)
    = text_field nil, nil, placeholder: "Search users"

app/views/wikis/_form.html.haml
#wiki-form.large-6.columns
  = simple_form_for @wiki do |f|
    = f.input :title, placeholder: 'Title'
    = f.input :body, label: "Body", placeholder: 'You can use Markdown here!', input_html: {rows: 14}
    - if current_user.premium? || current_user.admin?
      = f.input :private, label: "Make this private"
      %label Note that everyone may contribute by default if this is not a private wiki 
      = f.association :contributors, :collection => User.all, :label => 'Add Contributors (ctrl-click to select multiple)'
    = f.submit "Save", class: "button radius"
    = link_to "Preview", '#', class: 'button radius prev-btn'
#wiki-preview.large-6.columns
  - start_title = @wiki.title || 'Preview Area'
  - start_body = @wiki.body || '(You can use [Markdown](https://daringfireball.net/projects/markdown/) in your body to make this look pretty)'
  %h3= start_title
  #preview-body= markdown_to_html(start_body)

app/views/wikis/_wiki.html.haml
%ul#wiki-list
  %li{ :id => "wiki-#{wiki.id}" }
    = link_to wiki.title, wiki_path(wiki) 

app/views/wikis/edit.html.haml
%ul.breadcrumbs
  %li= link_to 'BLOCIPEDIA', root_path
  %li= link_to @wiki.user.name, user_path(@wiki.user)
  %li.current= @wiki.title
  %li.show-for-medium-up Created #{ @wiki.created_at.strftime('%B %e, %Y') }
  %li.hidden-for-medium-up Created #{ @wiki.created_at.strftime('%m/%d/%y') }
  - if (@wiki.created_at != @wiki.updated_at)
    %li.show-for-medium-up Edited #{ @wiki.updated_at.strftime('%B %e, %Y') }
    %li.hidden-for-medium-up Edited #{ @wiki.updated_at.strftime('%m/%d/%y') }

%h2 Edit this wiki
= render 'form'

app/views/wikis/new.html.haml
%h2 Make a New Wiki
= render 'form'

app/views/wikis/show.html.haml
%ul.breadcrumbs
  %li= link_to 'BLOCIPEDIA', root_path
  %li= link_to @wiki.user.name, user_path(@wiki.user)
  %li.current= @wiki.title
  %li.show-for-medium-up Created #{ @wiki.created_at.strftime('%B %e, %Y') }
  %li.hidden-for-medium-up Created #{ @wiki.created_at.strftime('%m/%d/%y') }
  - if (@wiki.created_at != @wiki.updated_at)
    %li.show-for-medium-up Edited #{ @wiki.updated_at.strftime('%B %e, %Y') }
    %li.hidden-for-medium-up Edited #{ @wiki.updated_at.strftime('%m/%d/%y') }
.wiki-show.row
  %h1= @wiki.title
  %p= markdown_to_html(@wiki.body)
  - if current_user && ( @wiki.user == current_user || current_user.admin? )
    = link_to 'Edit', edit_wiki_path(@wiki), class: 'button'
    = link_to 'Delete', wiki_path(@wiki), method: :DELETE, class: 'button alert', data: {confirm: 'Are you really sure you want to permanently this wiki?'}
  - if @wiki.private?
    .priv-notice This is a private wiki. Only its owner #{ link_to @wiki.user.name, user_path(@wiki.user)} and the following Blocipedia members may view or edit it:
    - @wiki.contributors.each do |c|
      %span= link_to c.name, user_path(c)